[workspace]
resolver = "2"
members = [
    "common",
    "create",
    "daemon",
    "dump-mnemonics",
    "test_client",
    "proto"
    , "tests/integration"]

[workspace.package]
rust-version = "1.85.0"
version = "0.1.1"
edition = "2024"
authors = ["Kaspa Developers", "IgraNet Developers"]
license = "ISC"
repository = "https://github.com/IgraLabs/kaswallet"
include = [
    "src/**/*.rs",
    "src/**/*.s",
    "src/**/*.r",
    "proto/**/*.proto",
    "benches/**/*.rs",
    "build.rs",
    "Cargo.toml",
    "Cargo.lock",
]

[workspace.dependencies]
kaswallet-common = { path = "common" }
kaswallet-proto = { path = "proto" }
kaswallet-daemon = { path = "daemon" }

kaspad = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-consensus = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-consensus-core = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-bip32 = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-utils = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-testing-integration = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-hashes = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-addresses = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-rpc-core = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-grpc-client = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-txscript = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }
kaspa-wallet-core = { git = "https://github.com/IgraLabs/rusty-kaspa.git" }

serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
argon2 = { version = "0.5.3", features = ["std"] }
chacha20poly1305 = { version = "0.10.1" }
hex = "0.4.3"
rand_core = "0.9.2"
regex = "1.11.1"
shellexpand = "3.1.0"
log = "0.4.26"
thiserror = "2.0.17"
borsh = "1.5.7"
clap = { version = "4.5.31", features = ["derive"] }
rpassword = "7.3.1"
constant_time_eq = "0.4.0"
itertools = "0.14.0"
log4rs = "1.3.0"
tokio = "1.43.0"
workflow-websocket = "0.18.0"
console-subscriber = "0.5.0"
futures = "0.3.31"
prost = "0.13"  # Keep prost and tonic versions to be the same as in rusty-kaspa.
tonic = { version = "0.12.3", features = ["tls-webpki-roots", "gzip", "transport"] }
tonic-build = { version = "0.12.3", features = ["prost"] }
rstest = "0.26.1"
tempfile = "3.23.0"
