[workspace]
resolver = "2"
members = [
    "core",
    "create",
    "daemon",
]

[workspace.package]
rust-version = "1.82.0"
version = "0.1.0"
edition = "2021"
authors = ["Kaspa Developers", "IgraNet Developers"]
license = "ISC"

[workspace.dependencies]
kaswallet-create = { path = "create" }
kaswallet-daemon = { path = "daemon" }
rusty-kaspa = { path = "../rusty-kaspa" }