[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kaswallet-daemon"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
wallet_proto = { path = "../wallet_proto" }
clap = { version = "4.5.31", features = ["derive"] }
kaspa-consensus-core = { path = "../../rusty-kaspa/consensus/core" }
kaspa-wrpc-client = {path = "../../rusty-kaspa/rpc/wrpc/client"}
log = "0.4.14"
log4rs = "1.3.0"
tonic = "0.12.3"
tokio = "1.43.0"
workflow-websocket = "0.18.0"