[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
name = "common"
crate-type = ["cdylib", "lib"]

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
rand = "0.9.0"
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
kaspa-consensus-core = { path = "../../rusty-kaspa/consensus/core" }
kaspa-bip32 = { path = "../../rusty-kaspa/wallet/bip32" }
hex = "0.4.3"
rand_core = "0.9.2"
regex = "1.11.1"
shellexpand = "3.1.0"

prost = "0.13.5"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1.17"
async-stream = "0.3.6"
log = "0.4.26"

[build-dependencies]
tonic-build = "0.12.3"